### ISSUE TITLE
【解惑】能請教你是怎麽通過NewTerminal為商品後面添加名稱翻譯的嗎？

### ISSUE THREAD

**Issue by CoolLKKPS** [XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization#11]
@XoF-eLtTiL 我一直搞不明白這點，因爲你能做到版本更新後還能正常在商品列表中追加新的商品内容（即沒翻譯的Cruiser、Belt Bag、Weed Killer，你沒翻譯但依舊能顯示在商品列表），而且我主要是好奇最核心的，你到底是怎麽為那些商品名稱後面添加自己的翻譯文本的？因爲那樣翻譯的話能顯示折扣之後的價格，這也是我最好奇的。我事實上也想做一份簡中的漢化，如果你能把這個技術發到Thunderstore模組社區裡就更好了

已編輯：`Github上有告知沒有開源許可證的儲存庫不屬於開源`，但你的一些成果其實很容易拷貝，我建議你添加開源許可證；我也希望知道你怎麽做到在商品後面添加翻譯文本的，在有開源許可證的幫助下獲得你的幫助我認爲會更順理成章，我的猜測是你修改了NewTerminal這個模組（其有自己的許可證），但我已經很難學到代碼上的知識了雖然我很想參與。

**Comment by XoF-eLtTiL** [comment]
這個主要是 我寫的 Terminal 是採用抓去片句翻譯，所以就算有更新新東西 也不會影響到其他模組的使用或是版本的更新

**Comment by XoF-eLtTiL** [comment]
那目前我在嘗試寫出額外輸出翻譯文件 可以做到即時修改翻譯 因為大部分翻譯我都是寫在代碼裡面的

**Comment by XoF-eLtTiL** [comment]
還有一個缺點 這個不相容其他會改終端機格式的模組 但是模組添加的物品開始可以正常使用

**Comment by CoolLKKPS** [comment]
> 這個主要是 我寫的 Terminal 是採用抓去片句翻譯，所以就算有更新新東西 也不會影響到其他模組的使用或是版本的更新

是的，我目前需要這項功能也主要在於一些模組物品翻譯我沒辦法自行更改，而使用者通常會認爲我沒嘗試去做這個事；如果按照NewTerminal的做法，即使的確可以做好，但按照我對我modpack的更新速率，我很難每次都去看商店内會推出什麽新内容（甚至可能直接忽略）

> 那目前我在嘗試寫出額外輸出翻譯文件 可以做到即時修改翻譯 因為大部分翻譯我都是寫在代碼裡面的
> 還有一個缺點 這個不相容其他會改終端機格式的模組 但是模組添加的物品開始可以正常使用

事實上我的modpack有許多會影響到終端的，除了Threat類的`Herobrine`，還有`TerminalFormatter`、`LCV`（作者是AMRV，對它其實會影響終端，蠻意外的）、`Terminal API`還有`Interactive_Terminal_API`，我不知道其他的，但我會用到的就這些
因爲目前主要只是要翻譯商品頁面和星球頁面，並讓這些頁面可以隨時更新就可以滿足我的需求，其實大頭的是`CustomStoryLogs`，這個是自定義模組日志，我記得`NewTerminal`是翻譯不了的
我對終端翻譯的最佳預期是讓星球頁面始終使用配對整個詞句翻譯，即當使用者輸入**moons**這個cmd時，禁止`NewTerminal`介入並且僅這一整個頁面改用全詞配對翻譯，然後允許全詞配對翻譯`[buyableItemsList]`、`[buyableVehiclesList]`、`[unlockablesList]`中的内容；如果翻譯者決定使用`regex`（正則表達式），則要求語句大小寫也必須配對無論在使用了regex提示詞之後是否使用了正則表達式；最後就是in-game translate，即我只需要退出到主菜單再重進就能看到我的翻譯，能更好的確認翻譯效果

**Comment by CoolLKKPS** [comment]
這些是我想比較久的反饋，而且我也希望我的翻譯能有用
記得沒錯的話，存儲頁面也有具備可變量的列表，但我目前忘記指代它的函數名叫什麽了，應該也叫`[unlockablesList]`我認爲

**Comment by XoF-eLtTiL** [comment]
畢竟 我不是參考New Terminal 的模組寫法

這個其實來自一個俄羅斯翻譯的使用方法，他的翻譯手法很硬核

針對每個特定區域，建立一個函數，在進行文字替換，確保不會浪費時間在替換其他不存在文字，也能確保不會衝突到其他會使用 Terminal 的模組

**Comment by XoF-eLtTiL** [comment]
我是依照那個想法寫出一個對應的

**Comment by XoF-eLtTiL** [comment]
我之後再針對 Terminal 模組開源 不過我要花點時間整理

**Comment by CoolLKKPS** [comment]
編輯：我想我知道該怎麽做了，雖然致命公司的本土化翻譯的使用體驗讓我感覺不舒服，但總的來説我開始有計劃去做這件事了

**Comment by CoolLKKPS** [comment]
在這之前我會好好等你的 Terminal 模組開源
