### ISSUE TITLE
[authorize] 请求繁中转简中的授权

### ISSUE THREAD

**Issue by HK417KEN** [XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization#5]
咨询：繁中转简中的授权问题
游戏：Lethal Company

###### 【简中汉化者】：上传简中Mod至Thunderstore的EggFriedRice [\[Thunderstore\]](https://thunderstore.io/c/lethal-company/p/EggFriedRice/Lethal_Company_CN_Localization_Simplified_Chinese/) [\[GitHub\]](https://github.com/xiahualiu/lethal_zh_mod)

作者您好，我以您的繁中汉化的 *7个文件* 为基底，与 *简中汉化者* 提供的简中汉化逐个比对进而优化了简中的游戏体验。

这是我替换完成后的文本，该仓库为临时展示而用，您不同意授权或展示目的完成后我将删除该仓库：
https://github.com/HK417KEN/LCTCToScShowcase

非常感谢您的原文提取及各种正则编写，请问您能 **授权** 我将这些内容以及您繁中的 **后续更新** 转换简中后再提供给 *简中汉化者* 或者我在Thunderstore+GitHub上自行上传维护一个新的简中Mod来服务简中玩家吗？

我会要求 *简中汉化者* 或者在我自行维护的README文档中添加感谢内容。

<br>

—— 申请人：HK417KEN 

<br>
<br>

---
###### 因为没有找到您的Email地址故无法以邮件的形式发送本文，除此之外我亦不清楚该发issue还是应该直接在X上DM您，如有错误，请多指教。

**Comment by XoF-eLtTiL** [comment]
不好意思，目前這個不開放

這個目前還是會繼續頻繁更新，還沒有最終版本，

目前遊戲主要內容還在針對 V47 準備更新

**Comment by XoF-eLtTiL** [comment]
不過我目前授權你可以轉換，但是必須在Mod頁面上標註原作者

**Comment by HK417KEN** [comment]
> 不過我目前授權你可以轉換，但是必須在Mod頁面上標註原作者

好的，谢谢！

**Comment by HK417KEN** [comment]
如果更改授权或其他任何情况可随时与我联系：HK417KEN@gmail.com

既然问题解决了那就关闭issue了，祝您生活愉快！
