### ISSUE TITLE
字體和FontPatcher Plugin的個人看法

### ISSUE THREAD

**Issue by CoolLKKPS** [XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization#7]
簡中的支援能更好的與同樣能用漢語溝通的人交流，我覺得即使我沒有對簡中有非常嚴重的需求，但有時看他們發的消息全是unicode的口口字的確無法理解，希望能再努力一把做個簡中的支援！
然後是FontPatcher Plugin，我覺得完全可以給任何國家的做本土化工作的人提供這個Unity Plugin，我的建議是上傳到Thunderstore，這樣讓這個工具能發揮其真正的價值，當然這是我的看法，我認爲你做的真的很棒，不希望這個工具就局限在本土化

**Comment by XoF-eLtTiL** [comment]
Font patcher並不是我原創的，這個來自一個韓國的開發者，但是他又開源項目，我有進行修改 取代字體 的程式碼

**Comment by XoF-eLtTiL** [comment]
則字體呢就是我用原創的合併方法了
