### ISSUE TITLE
[Error  : Unity Log] 更多的兼容性報錯

### ISSUE THREAD

**Issue by CoolLKKPS** [XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization#8]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NewTerminalDetected.UIPatches+UniversalUIPatches.OnPreInitMenuShown () (at <6c01ed2255864495961201e4830ab93b>:0)
(wrapper dynamic-method) PreInitSceneScript.DMD<PreInitSceneScript::Start>(PreInitSceneScript)

可能是小問題

**Comment by CoolLKKPS** [comment]
@XoF-eLtTiL 這裡會列出一些產生衝突時所記錄的日志，這還會導致LLL無法載入存檔

[00:39:45.7471131] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DontTouchMe.Assets.Init () (at <407671742ac04945adcd454e47301576>:IL_0016)
DontTouchMe.Plugin.Awake () (at <407671742ac04945adcd454e47301576>:IL_019F)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[00:39:45.7471131] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DontTouchMe.Assets.Init () (at <407671742ac04945adcd454e47301576>:IL_0016)
DontTouchMe.Plugin.Awake () (at <407671742ac04945adcd454e47301576>:IL_019F)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[00:39:45.8044373] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384)
Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111)
Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[00:39:45.8044373] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384)
Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111)
Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[00:39:45.8044373] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384)
Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111)
Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[00:39:45.8044373] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384)
Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111)
Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

原因是`EnableTextAssetRedirector=True`

**Comment by CoolLKKPS** [comment]
因爲這些衝突，我重新製作了一個新的配置文件檔用於解決這些原本不應該發生的問題，好在這是能夠輕易排查出並解決的
因爲强迫症，我未來會固定使用並備份這個配置檔
[AutoTranslatorConfig.txt](https://github.com/XoF-eLtTiL/LCTC/files/15123661/AutoTranslatorConfig.txt)

**Comment by CoolLKKPS** [comment]
另外，我現在絕對需要能在FontPatcher中能用的簡體中文字體，或許你可以考慮下？

**Comment by XoF-eLtTiL** [comment]
感謝你的回報，會開始進行測試調適

簡體中文的字體我可能會在想辦法寫在Fontpatcher

**Comment by CoolLKKPS** [comment]
關於需要簡中字體支援的需求，我認為我的modpack需要支持盡可能多的中文，我的modpack不只是因為社區的努力，我還需要感謝我的大陸朋友為我的modpack進行非常多深入的測試，無論他的技術還是對我遊戲技術的包容，如果沒有他的幫助，我不認為我的modpack可以達到能用於廣泛測試模組的標準，而我也不會一直堅持每天更新我的modpack，這也是我希望我的modpack能夠有簡中的原因之一
我已經堅持每天更新modpack已經近4個月了，尤其是v50的更新非常巨量，那個時候的疲勞程度有過於那時更新v49的modpack，不過最近的更新緩和了很多，不過如果你有足夠充足的精力，我能把我的modpack發給你來讓你做本土化支援

**Comment by CoolLKKPS** [comment]
fontpatcher的優勢是更深入的讓遊戲支援多種字體

**Comment by XoF-eLtTiL** [comment]
大概需要點時間，我正在調整簡體中文的字體，因為我在做這些字體時候會想辦法對應遊戲風格，就是不平滑類似電子顯示的腳果

**Comment by XoF-eLtTiL** [comment]
> fontpatcher的優勢是更深入的讓遊戲支援多種字體

所以我應該會在 1.2.3 做 FIX 更新和簡體中文的字庫加入

**Comment by XoF-eLtTiL** [comment]
> @XoF-eLtTiL 這裡會列出一些產生衝突時所記錄的日志，這還會導致LLL無法載入存檔
> 
> [00:39:45.7471131] [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: DontTouchMe.Assets.Init () (at <407671742ac04945adcd454e47301576>:IL_0016) DontTouchMe.Plugin.Awake () (at <407671742ac04945adcd454e47301576>:IL_019F) UnityEngine.GameObject:AddComponent(Type) BepInEx.Bootstrap.Chainloader:Start() UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
> 
> [00:39:45.7471131] [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: DontTouchMe.Assets.Init () (at <407671742ac04945adcd454e47301576>:IL_0016) DontTouchMe.Plugin.Awake () (at <407671742ac04945adcd454e47301576>:IL_019F) UnityEngine.GameObject:AddComponent(Type) BepInEx.Bootstrap.Chainloader:Start() UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
> 
> [00:39:45.8044373] [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384) Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111) Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception. UnityEngine.GameObject:AddComponent(Type) BepInEx.Bootstrap.Chainloader:Start() UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
> 
> [00:39:45.8044373] [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384) Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111) Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception. UnityEngine.GameObject:AddComponent(Type) BepInEx.Bootstrap.Chainloader:Start() UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
> 
> [00:39:45.8044373] [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384) Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111) Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception. UnityEngine.GameObject:AddComponent(Type) BepInEx.Bootstrap.Chainloader:Start() UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
> 
> [00:39:45.8044373] [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: Kittenji.Assets..ctor (System.String name) (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/.utils/Assets.cs:384) Kittenji.HerobrineMod.Plugin..cctor () (at C:/Users/chris/Documents/Scripts/VSModding/LethalCompanyNET/HerobrineMod/Plugin.cs:111) Rethrow as TypeInitializationException: The type initializer for 'Kittenji.HerobrineMod.Plugin' threw an exception. UnityEngine.GameObject:AddComponent(Type) BepInEx.Bootstrap.Chainloader:Start() UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
> 
> 原因是`EnableTextAssetRedirector=True`

這個我後來發現到我在早期測試所有XUnity 功能時候忘記關掉，沒想到會影響後續的相容性

**Comment by XoF-eLtTiL** [comment]
> 關於需要簡中字體支援的需求，我認為我的modpack需要支持盡可能多的中文，我的modpack不只是因為社區的努力，我還需要感謝我的大陸朋友為我的modpack進行非常多深入的測試，無論他的技術還是對我遊戲技術的包容，如果沒有他的幫助，我不認為我的modpack可以達到能用於廣泛測試模組的標準，而我也不會一直堅持每天更新我的modpack，這也是我希望我的modpack能夠有簡中的原因之一 我已經堅持每天更新modpack已經近4個月了，尤其是v50的更新非常巨量，那個時候的疲勞程度有過於那時更新v49的modpack，不過最近的更新緩和了很多，不過如果你有足夠充足的精力，我能把我的modpack發給你來讓你做本土化支援

了解 不過目前翻譯 Mod 還在列表中，因為主要 Mod 很多 
我可能沒辦法翻譯所有Mod，只能說 玩到什麼就翻譯什麼吧OWO
當然，我也會到處下載新模組然後嘗試遊玩翻譯，不過目前來講我應該會翻譯目前主要功能像是 LLL 和 LCV 這類的主要常用模組

**Comment by CoolLKKPS** [comment]
啊哈，沒問題，這個包可以分享給你玩，glhf!
Link: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h?

**Comment by XoF-eLtTiL** [comment]
> 啊哈，沒問題，這個包可以分享給你玩，glhf! Link: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h?

謝謝 
也感謝你的回報 大部分已經修好了，正在做最後確認
